<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>1g Price - Swatch</name>
   <tag></tag>
   <elementGuidId>aab5a353-e932-498e-813c-d6651fd1daa9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>body.header--sticky:nth-child(2) div.main:nth-child(6) section.product:nth-child(2) div.container:nth-child(1) div.row div.product__info form.variant-selector div.section div.variant-selector__option-selectors div.section ul.swatches li.swatch.swatch--weight:nth-child(1) > span.swatch__price</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='suggested-accessories__tab--bongs-pipes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>swatch__price</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div[3]/section/div[1]/div[2]/div[2]/form/div/div[1]/div/ul/fieldset/li[1]/span[1]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>body.header--sticky:nth-child(2) div.main:nth-child(6) section.product:nth-child(2) div.container:nth-child(1) div.row div.product__info form.variant-selector div.section div.variant-selector__option-selectors div.section ul.swatches li.swatch.swatch--weight:nth-child(1) > span.swatch__price</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <value>//li[@id='suggested-accessories__tab--bongs-pipes']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='shopify-section-en-suggested-accessories']/div/div/div[2]/div/ul/li[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Papers &amp; Filters'])[3]/following::li[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vaporizers'])[2]/following::li[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CanaCrush'])[1]/preceding::li[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div/div/div[2]/div/ul/li[4]</value>
   </webElementXpaths>
</WebElementEntity>
